version: '3.3'
services:
  app:
    build: .
    ports:
      - 3000:3000
    networks:
      - nat
  redis:
    image: alexellisio/redis-windows:3.2
    networks:
      - nat
networks:
  nat:
    external: true