version: "3.3"

services:
  api:
    build:
      context: api
    image: ddev_api
    ports:
      - 5000:5000
    networks:
      - nat
    volumes:
      - ./devsecrets:c:/ProgramData/Docker/secrets

  ui:
    build:
      context: ui
    image: ddev_ui
    ports:
      - 3000:3000
    networks:
      - nat

secrets:
  sql_password:
    file: ./devsecrets/sql_password

networks:
  nat:
    external: true
